name: Build Docker Images with Kratos

on:
  pull_request:
    paths:
    - 'scripts/docker_files/docker_file_kratos_ubuntu_bionic/DockerFile'
    - '.github/workflows/build_docker_images_with_kratos.yml'

  schedule:
    - cron: '0 0 * * *' # update it every night at midnight

jobs:
  build-ubuntu-docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file scripts/docker_files/docker_file_kratos_ubuntu_bionic/DockerFile --tag kratosmultiphysics/kratos-image-ubuntu-bionic
    - name: Docker Login
      uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Publish the Docker image
      run: docker push kratosmultiphysics/kratos-image-ubuntu-bionic


  run-nightly-test-ubuntu--docker:
    needs: build-ubuntu-docker
    runs-on: ubuntu-latest

    container:
      image: kratosmultiphysics/kratos-image-ubuntu-bionic:latest

    steps:
    - name: Running tests
      run: |
        # TODO those variables should be set automatically in the container!
        export MKLVARS_ARCHITECTURE=intel64
        export MKLVARS_INTERFACE=lp64
        . /opt/intel/mkl/bin/mklvars.sh
        export PYTHONPATH=${PYTHONPATH}:/software/Kratos/bin/Release
        export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/software/Kratos/bin/Release/libs
        python3 /software/Kratos/kratos/python_scripts/run_tests.py -l nightly -c python3
