name: Build and Publish the Kratos Wheels for PiPy

# on: # build the corresponding release branch
#     release:
#       types: [created]

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Build the wheels
      run: |
        mkdir wheels
        sudo docker run --rm -v ${GITHUB_WORKSPACE}/wheels:/workspace/out kratosmultiphysics/kratos-wheelbuilder-linux master 2
