name: Build and Publish the Kratos Wheels for PiPy

# on: # build the corresponding release branch
#     release:
#       types: [created]

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the wheels
    - run: sudo docker run --rm -v <local-output-dir>:${GITHUB_WORKSPACE}/wheels kratosmultiphysics/kratos-wheelbuilder-linux master 2
