name: Build and Publish the Kratos Wheels

# on: # build the corresponding release branch
#     release:
#       types: [created]

on: push

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [35, 36, 37, 38]

    steps:
    - name: Pull docker image
      run: sudo docker pull kratosmultiphysics/kratos-wheelbuilder-linux

    - name: Build wheels
      run: |
        mkdir wheels
        sudo docker run --rm -v ${GITHUB_WORKSPACE}/wheels:/workspace/out hubertus248/kratoswheelbuilder-linux --branch "wheels/add-action" --cpus 2 --pythons ${{ matrix.python-version }} --cotire ON

    - uses: actions/upload-artifact@v2
      with:
        name: Upload artifacts
        path:  ${GITHUB_WORKSPACE}/wheels/*

  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [35, 36, 37, 38]

    steps:
    - name: Pull docker image
      run: docker pull hubertus248/kratoswheelbuilder-win

    - name: Build wheels
      shell: pwsh
      run: |
        mkdir wheels
        docker run --rm --isolation=process -v wheels:c:\out kratosmultiphysics/kratos-wheelbuilder-windows -branch wheels/add-action -pythons "${{ matrix.python-version }}" -cotire ON -cpus 1

    - uses: actions/upload-artifact@v2
      with:
        name: Upload artifacts
        path: wheels/*