name: Build and Publish the Kratos Wheels for PiPy

# on: # build the corresponding release branch
#     release:
#       types: [created]

on: push

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
    - name: Build the wheels
      run: |
        mkdir wheels
        sudo docker run --rm -v ${GITHUB_WORKSPACE}/wheels:/workspace/out kratosmultiphysics/kratos-wheelbuilder-linux master 2

  windows:
    runs-on: windows-latest

    steps:
    - name: Build the wheels
      shell: pwsh
      run: |
        mkdir wheels
        docker run --rm --memory=4 --cpus=2 -v ${GITHUB_WORKSPACE}/wheels:c:\out kratosmultiphysics/kratos-wheelbuilder-windows master
