name: CI

on: [pull_request]

jobs:
  ubuntu:
    runs-on: ubuntu-latest

    container:
      image: oberbichler/kratos-dev:latest
      env:
        CCACHE_SLOPPINESS: pch_defines,time_macros
        CCACHE_COMPILERCHECK: content
        CCACHE_COMPRESS: true
        CCACHE_NODISABLE: true
        CCACHE_MAXSIZE: 500M
        FC: gfortran-7
        CC: /usr/lib/ccache/gcc
        CXX: /usr/lib/ccache/g++

    steps:
    - uses: actions/checkout@v2-beta
    - name: Cache Build
      id: cache-build
      uses: actions/cache@v1
      with:
        path: ~/.ccache
        key: ${{ runner.os }}-ccache-${{ github.sha }}
        restore-keys: ${{ runner.os }}-ccache-
    - name: Build
      run: |
        cp scripts/build/travis/configure_travis_bionic.sh configure.sh
        bash configure.sh
        ccache -s
    - name: Test
      run: |
        export PYTHONPATH=${PYTHONPATH}:${GITHUB_WORKSPACE}/bin/Custom
        export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${GITHUB_WORKSPACE}/bin/Custom/libs
        python3 kratos/python_scripts/run_tests.py -l small -c python3

  windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2-beta
      with:
        repository: KratosMultiphysics/Kratos
        ref: refs/heads/master
    - uses: actions/setup-python@v1
      with:
        python-version: '3.6'
    - name: Cache Build
      id: cache-build
      uses: actions/cache@v1
      with:
        path: build
        key: ${{ runner.os }}-build-${{ github.sha }}
        restore-keys: ${{ runner.os }}-build-
    - name: Build
      shell: cmd
      run: |
        call "%ProgramFiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64 || goto :error
        
        set CC=cl.exe
        set CXX=cl.exe
        
        set KRATOS_BUILD_TYPE=Release
        set KRATOS_SOURCE=%cd%
        set KRATOS_BUILD=%cd%\build
        set KRATOS_APP_DIR=applications
        
        cd %KRATOS_SOURCE%\applications\DelaunayMeshingApplication || goto :error
        mkdir external_modules || goto :error
        cd external_modules || goto :error
        curl -L https://github.com/PFEM/tetgen/archive/0f0c1c95388d9a515e2383533c6b4f18524d9e76.zip -o tetgen.zip || goto :error
        7z e tetgen.zip -o"tetgen" || goto :error
        cd %KRATOS_SOURCE% || goto :error
        
        set KRATOS_APPLICATIONS=
        set KRATOS_APPLICATIONS=%KRATOS_APPLICATIONS%%KRATOS_APP_DIR%\FluidDynamicsApplication;
        set KRATOS_APPLICATIONS=%KRATOS_APPLICATIONS%%KRATOS_APP_DIR%\StructuralMechanicsApplication;
        set KRATOS_APPLICATIONS=%KRATOS_APPLICATIONS%%KRATOS_APP_DIR%\ContactStructuralMechanicsApplication;
        set KRATOS_APPLICATIONS=%KRATOS_APPLICATIONS%%KRATOS_APP_DIR%\MeshingApplication;
        set KRATOS_APPLICATIONS=%KRATOS_APPLICATIONS%%KRATOS_APP_DIR%\MeshMovingApplication;
        set KRATOS_APPLICATIONS=%KRATOS_APPLICATIONS%%KRATOS_APP_DIR%\DEMApplication;
        set KRATOS_APPLICATIONS=%KRATOS_APPLICATIONS%%KRATOS_APP_DIR%\SwimmingDEMApplication;
        set KRATOS_APPLICATIONS=%KRATOS_APPLICATIONS%%KRATOS_APP_DIR%\CSharpWrapperApplication;
        set KRATOS_APPLICATIONS=%KRATOS_APPLICATIONS%%KRATOS_APP_DIR%\SolidMechanicsApplication;
        set KRATOS_APPLICATIONS=%KRATOS_APPLICATIONS%%KRATOS_APP_DIR%\ConstitutiveModelsApplication;
        set KRATOS_APPLICATIONS=%KRATOS_APPLICATIONS%%KRATOS_APP_DIR%\DelaunayMeshingApplication;
        set KRATOS_APPLICATIONS=%KRATOS_APPLICATIONS%%KRATOS_APP_DIR%\ContactMechanicsApplication;
        set KRATOS_APPLICATIONS=%KRATOS_APPLICATIONS%%KRATOS_APP_DIR%\PfemApplication;
        set KRATOS_APPLICATIONS=%KRATOS_APPLICATIONS%%KRATOS_APP_DIR%\PfemFluidDynamicsApplication;
        set KRATOS_APPLICATIONS=%KRATOS_APPLICATIONS%%KRATOS_APP_DIR%\PfemSolidMechanicsApplication;
        
        del /F /Q "%KRATOS_BUILD%\%KRATOS_BUILD_TYPE%\cmake_install.cmake"
        del /F /Q "%KRATOS_BUILD%\%KRATOS_BUILD_TYPE%\CMakeCache.txt" 
        del /F /Q "%KRATOS_BUILD%\%KRATOS_BUILD_TYPE%\CMakeFiles"
        
        cmake                                                ^
          -G"Visual Studio 16 2019"                          ^
          -H"%KRATOS_SOURCE%"                                ^
          -B"%KRATOS_BUILD%\%KRATOS_BUILD_TYPE%"             ^
          -DBOOST_ROOT="%BOOST_ROOT%"                        ^
          -DINCLUDE_FEAST=OFF                                ^
          -DINSTALL_RUNKRATOS=OFF                            ^
          -DUSE_COTIRE=ON                                    || goto :error
        
        cmake --build "%KRATOS_BUILD%\%KRATOS_BUILD_TYPE%" --target all_unity || goto :error
        
        :error
        echo Failed with error #%errorlevel%.
        exit /b %errorlevel%
