name: Docker Image for CI

on:
  pull_request:
    paths:
    - 'scripts/docker_files/docker_file_ci/DockerFile'
    - '.github/workflows/dockerimage_for_ci.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file scripts/docker_files/docker_file_ci/Dockerfile --tag kratosmultiphysics/kratos-image-ci
    - name: Docker Login
      uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Publish the Docker image
      run: docker push kratosmultiphysics/kratos-image-ci
